środa, 11 września 2019 08:35:42

--- Main exception: Message ---
Wywołanie zwrotne użytkownika zgłosiło wyjątek. Sprawdź stos wyjątków i wewnętrzny wyjątek w celu określenia wywołania zwrotnego, które zakończyło się niepowodzeniem.

--- Inner exception 1: Message ---
Usługa HPWEBService zerwała połączenie. Nie ma możliwości powtórnego zalogowania się. Zrestartuj aplikację

--- Inner exception 1: StackTrace ---
   w DataLayer.Implementation.GatewayDaoWFS.Channel_Faulted(Object obj, EventArgs arg) w C:\CP\ParserGit\JiraParser\DataLayer\Implementation\GatewayDaoWFS.cs:wiersz 275
   w DataLayer.ServiceManager.Channel_Fault(Object sender, EventArgs e) w C:\CP\ParserGit\JiraParser\DataLayer\ServiceManager.cs:wiersz 27
   w System.ServiceModel.Channels.CommunicationObject.OnFaulted()

--- Inner exception 1: Source ---
DataLayer

--- Main exception: StackTrace ---
   w System.ServiceModel.Channels.CommunicationObject.OnFaulted()
   w System.ServiceModel.Channels.CommunicationObject.Fault()
   w System.ServiceModel.Channels.ServiceChannel.OnInnerChannelFaulted(Object sender, EventArgs e)
   w System.ServiceModel.Channels.CommunicationObject.OnFaulted()
   w System.ServiceModel.Channels.CommunicationObject.Fault()
   w System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   w System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   w System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   w System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   w System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   w System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   w System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   w System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   w System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
   w System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   w DataLayer.HPDataService.IDataService4HP.LogIn2(String login, String pass)
   w DataLayer.Implementation.GatewayDaoWFS.loginToWFSWithUserInfo(String user, String password) w C:\CP\ParserGit\JiraParser\DataLayer\Implementation\GatewayDaoWFS.cs:wiersz 263
   w LogicLayer.Implementation.ParserEngineWFS.loginToWFSWithUserInfo(String username, String password) w C:\CP\ParserGit\JiraParser\Logic\Implementation\ParserEngineWFS.cs:wiersz 46
   w GUI.Login.<invokeLogin>b__27_0() w C:\CP\ParserGit\JiraParser\GUI\LoginForm.cs:wiersz 109

--- Main exception: Source ---
System.ServiceModel

